name: quicksort
description: quicksort algorithm
# version: 1.0.0
# homepage: bnt.now.sh/quicksort

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
